# Generated by Django 4.2.4 on 2023-10-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inoa", "0003_alter_email_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
