# Generated by Django 4.2.4 on 2023-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inoa", "0004_alter_email_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo", name="precos", field=models.JSONField(default=list),
        ),
    ]
